### PR TITLE
Fix error calculation in MATLAB_Octave tutorial

### LINKED ISSUE #349: MATLAB_OCTAVE Two way wave equation error calculation is wrong
**Describe the bug**
The error calculation in the matlab_octave/tutorial/two_way_wave_equation is wrong.

**To Reproduce**
Run the tutorial.

**Expected behavior**
Finite difference example should stay around order 2, mimetic should increase through 2,4,6ish.

**Screenshots**
Here is the second order operators not being second order.

Image

### PR DESCRIPTION
**Pull request by jbrzensk**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [ ] Feature
- [X] Bug Fix
- [ ] Optimization
- [ ] Example
- [ ] Documentation

## Description
Fixes the bug in the MATLAB/Octave tutorial where changing the order of accuracy of the mimetic operator does nothing. The errors calculated are essentially the same regardless of order of accuracy.

## Related Issues & Documents
- [X] I have created an Issue that is paired with this PR
- Closes #349 

## QA Instructions, Screenshots, Recordings
image

image

## Added/updated tests?

- [ ] Yes
- [X] No, and this is why: tutorial not a test.
- [ ] I need help with writing tests

## Read Contributing Guide and Code of Conduct

- [X] 📖 I have read the MOLE Contributing Guide: https://github.com/csrc-sdsu/mole/blob/main/CONTRIBUTING.md
- [X] 📖 I have read the MOLE Code of Conduct: https://github.com/csrc-sdsu/mole/blob/main/CODE_OF_CONDUCT.md

### CODE REVIEW

File: examples/matlab_octave/tutorials/two_way_wave_equation/finite_diff_two_way_wave_eq.m [hunk 1]
```diff
@@ -39,20 +44,17 @@
...
-%% Number of cells to try, grid points is cells+1
-num_cells = [ 10, 20, 40, 80, 160 ];
-
 % generic holders for metrics within the loops
 error_fd = zeros(size(num_cells));
 walltime_fd = zeros(size(num_cells));
 flops_fd = zeros(size(num_cells));
 
-% Initial Condition Function
+% Initial Condition Function (One smooth, one smoother)
```
Comment (valeriabarra) [inline examples/matlab_octave/tutorials/two_way_wave_equation/finite_diff_two_way_wave_eq.m]: Why one smooth and another one smoother function?

Comment (jbrzensk) [reply examples/matlab_octave/tutorials/two_way_wave_equation/finite_diff_two_way_wave_eq.m]: Holdover from our lesson, the second function is smoother. I'll remove the first and the comment to reduce confusion.

File: examples/matlab_octave/tutorials/two_way_wave_equation/comparison_two_way_wave_md_vs_fd.m
Comment (valeriabarra) [inline examples/matlab_octave/tutorials/two_way_wave_equation/comparison_two_way_wave_md_vs_fd.m]: I know this was not touched in this PR, but can we homogenize these figure titles please? The Walltime one only mentions the MD order. The FLOPs one reads "FLOPs for each method, mimetic order:" and concatenates the mimetic order. The first figure, the one with the error, mentions both order. Can we make them consistent? Perhaps we should remind the user/reader about both orders in all figures?

**Comment by valeriabarra** [comment]
Pending my comment on figure titles cleanup, this looks good to me otherwise. Thank you!

File: examples/matlab_octave/tutorials/two_way_wave_equation/comparison_two_way_wave_md_vs_fd.m
Comment (jbrzensk) [reply examples/matlab_octave/tutorials/two_way_wave_equation/comparison_two_way_wave_md_vs_fd.m]: OK, 
image

image

**Review by valeriabarra — APPROVED** [review]
